### ISSUE TITLE
REQ

### ISSUE THREAD

**Issue by Chichaa30** [namhoang2210/tvassd#1]
Can you add a Category Filter Menu? I hope you add it to this Script. Thanks

**Comment by namhoang2210** [comment]
> Can you add a Category Filter Menu? I hope you add it to this Script. Thanks
ok bro, i will update early.

**Comment by Chichaa30** [comment]
> > Bisakah Anda menambahkan Menu Filter Kategori? Saya harap Anda menambahkannya ke Script ini. Thanks 
> > ok gan, ane update duluan.

Ok sir, I'm waiting 👍 Cool project!
